# Book settings
title: "Test CD Jupyter notebook"
author: Gilles
logo: 'logo.jpg'
# Bibliography
bibtex_bibfiles:
  - refs.bib
sphinx:
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite
